--tao csdl qlbanhang
DROP TABLE N09_NHANVIEN CASCADE CONSTRAINTS;
DROP TABLE N09_BOPHAN CASCADE CONSTRAINTS;
DROP TABLE N09_BAOCAO CASCADE CONSTRAINTS;
DROP TABLE N09_LOAIBC CASCADE CONSTRAINTS;
DROP TABLE N09_SANPHAM CASCADE CONSTRAINTS;
DROP TABLE N09_LOAISP CASCADE CONSTRAINTS;
DROP TABLE N09_HOADONBANHANG CASCADE CONSTRAINTS;
DROP TABLE N09_CTHDBH CASCADE CONSTRAINTS;
DROP TABLE N09_HOADONNHAPHANG CASCADE CONSTRAINTS;
DROP TABLE N09_CTHDNH CASCADE CONSTRAINTS;


CREATE TABLE N09_NHANVIEN
(
    MANV VARCHAR(5),
    HOTEN NVARCHAR2(50),
    PHAI NVARCHAR2(10),
    NGAYSINH DATE,
    DIENTHOAI CHAR(12),
    BPLAMVIEC VARCHAR(5),
    MUCLUONG INT,
    MANQL VARCHAR(5),
    
    PRIMARY KEY(MANV)
);

CREATE TABLE N09_BOPHAN
(
    MABP VARCHAR(5),
    TENBP NVARCHAR2(50),
    
    PRIMARY KEY (MABP)
);

CREATE TABLE N09_BAOCAO
(
    MABC VARCHAR(5),
    TENBC NVARCHAR2(50),
    LOAIBC VARCHAR(5),
    NGUOILAP VARCHAR(5),
    NGUOINHAN VARCHAR(5),
    NGAYLAP DATE,
    
    PRIMARY KEY(MABC)
);

CREATE TABLE N09_LOAIBC
(
    MALOAIBC VARCHAR(5),
    TENLOAIBC NVARCHAR2(50),
    
    PRIMARY KEY(MALOAIBC)
);

CREATE TABLE N09_SANPHAM
(
    MASP VARCHAR(5),
    TENSP NVARCHAR2(50),
    LOAISP VARCHAR(5), 
    SOLUONGTON INT,
    GIANHAP INT,
    GIABAN INT,
    TINHTRANG NVARCHAR2(50),
       
    PRIMARY KEY(MASP)
);

CREATE TABLE N09_LOAISP
(
    MALOAISP VARCHAR(5),
    TENLOAISP NVARCHAR2(50),
    
    PRIMARY KEY(MALOAISP)
);

CREATE TABLE N09_HOADONBANHANG
(
    MAHD VARCHAR(5),
    NGAYLAP DATE,
    TONGTIEN INT,
    NGUOILAP VARCHAR(5),
    
    PRIMARY KEY(MAHD)
);

CREATE TABLE N09_CTHDBH
(
    MAHD VARCHAR(5),
    MASP VARCHAR(5),
    SOLUONG INT,
    GIABAN INT,
    
    PRIMARY KEY(MAHD, MASP)
);

CREATE TABLE N09_HOADONNHAPHANG
(
    MAHD VARCHAR(5),
    NGAYLAP DATE,
    TONGTIEN INT,
    NGUOILAP VARCHAR(5),
    
    PRIMARY KEY(MAHD)
);

CREATE TABLE N09_CTHDNH
(
    MAHD VARCHAR(5),
    MASP VARCHAR(5),
    SOLUONG INT,
    GIANHAP INT,
    
    PRIMARY KEY(MAHD, MASP)
);

-- khóa ngoại 
ALTER TABLE N09_NHANVIEN
ADD
    CONSTRAINT FK_NV_BP 
    FOREIGN KEY (BPLAMVIEC)
    REFERENCES N09_BOPHAN;
    
ALTER TABLE N09_NHANVIEN
ADD
    CONSTRAINT FK_NV_NV_
    FOREIGN KEY (MANQL)
    REFERENCES N09_NHANVIEN;

ALTER TABLE N09_BAOCAO
ADD
    CONSTRAINT FK_BC_LBC
    FOREIGN KEY (LOAIBC)
    REFERENCES N09_LOAIBC;

ALTER TABLE N09_SANPHAM
ADD
    CONSTRAINT FK_SP_LSP
    FOREIGN KEY (LOAISP)
    REFERENCES N09_LOAISP;

ALTER TABLE N09_CTHDBH
ADD
    CONSTRAINT FK_CTHDN09_HD
    FOREIGN KEY (MAHD)
    REFERENCES N09_HOADONBANHANG;

ALTER TABLE N09_CTHDBH
ADD
    CONSTRAINT FK_CTHDN09_SP
    FOREIGN KEY (MASP)
    REFERENCES N09_SANPHAM;

ALTER TABLE N09_HOADONBANHANG
ADD
    CONSTRAINT FK_CTHDN09_NV
    FOREIGN KEY (NGUOILAP)
    REFERENCES N09_NHANVIEN;

ALTER TABLE N09_CTHDNH
ADD
    CONSTRAINT FK_CTHDNH_HD
    FOREIGN KEY (MAHD)
    REFERENCES N09_HOADONNHAPHANG;

ALTER TABLE N09_CTHDNH
ADD
    CONSTRAINT FK_CTHDNH_SP
    FOREIGN KEY (MASP)
    REFERENCES N09_SANPHAM;
    
ALTER TABLE N09_HOADONNHAPHANG
ADD
    CONSTRAINT FK_CTHDNH_NV
    FOREIGN KEY (NGUOILAP)
    REFERENCES N09_NHANVIEN;
    