-- Lớp: CQ2021/1
-- Nhóm: 09
-- Thành viên:
-- 21120037 - Mã Thùy Anh
-- 21120060 - Nguyễn Long Giang
-- 21120082 - Phan Quốc Huy 
-- 21120117 - Lê Thị Hồng Phượng



----------------------------------------------------------------
-- Tạo cấu trúc
----------------------------------------------------------------
-- Xóa các bảng và user trước khi chạy script
DROP TABLE N09_NHANSU CASCADE CONSTRAINTS;
DROP TABLE N09_SINHVIEN CASCADE CONSTRAINTS;
DROP TABLE N09_DONVI CASCADE CONSTRAINTS;
DROP TABLE N09_HOCPHAN CASCADE CONSTRAINTS;
DROP TABLE N09_KHMO CASCADE CONSTRAINTS;
DROP TABLE N09_PHANCONG CASCADE CONSTRAINTS;
DROP TABLE N09_DANGKY CASCADE CONSTRAINTS;
/

-- Tạo CSDL
CREATE TABLE N09_NHANSU
(
    MANV CHAR(5),
    HOTEN NVARCHAR2(30),
    PHAI NVARCHAR2(3),
    NGSINH DATE,
    PHUCAP NUMBER(10),
    DT CHAR(10),
    VAITRO NVARCHAR2(30),
    MADV CHAR(5),
    
    PRIMARY KEY(MANV)
);

CREATE TABLE N09_SINHVIEN
(
    MASV CHAR(5),
    HOTEN NVARCHAR2(30),
    PHAI NVARCHAR2(3),
    NGSINH DATE,
    DIACHI NVARCHAR2(30),
    DT CHAR(10),
    MACT NVARCHAR2(30),
    MANGANH NVARCHAR2(30),
    SOTCTL NUMBER(4),
    DTBTL NUMBER(4,2),
    
    PRIMARY KEY(MASV)
);

CREATE TABLE N09_DONVI
(
    MADV CHAR(5),
    TENDV NVARCHAR2(30),
    TRGDV CHAR(5),
    
    PRIMARY KEY(MADV)
);

CREATE TABLE N09_HOCPHAN
(
    MAHP CHAR(5),
    TENHP NVARCHAR2(30),
    SOTC NUMBER(2),
    STLT NUMBER(4),
    STTH NUMBER(4),
    SOSVTD NUMBER(4),
    MADV CHAR(5),
    
    PRIMARY KEY(MAHP)
);

CREATE TABLE N09_KHMO
(
    MAHP CHAR(5),
    HK NUMBER(1),
    NAM NUMBER(4),
    MACT VARCHAR(4),
    
    PRIMARY KEY(MAHP, HK, NAM, MACT)
);

CREATE TABLE N09_PHANCONG
(
    MAGV CHAR(5),
    MAHP CHAR(5),
    HK NUMBER(1),
    NAM NUMBER(4),
    MACT VARCHAR(4),
    
    PRIMARY KEY(MAGV, MAHP, HK, NAM, MACT)
);

CREATE TABLE N09_DANGKY
(
    MASV CHAR(5),
    MAGV CHAR(5),
    MAHP CHAR(5),
    HK NUMBER(1),
    NAM NUMBER(4),
    MACT VARCHAR(4),
    DIEMTH NUMBER(4,2),
    DIEMQT NUMBER(4,2),
    DIEMCK NUMBER(4,2),
    DIEMTK NUMBER(4,2),
    
    PRIMARY KEY(MASV, MAGV, MAHP, HK, NAM, MACT)
);

-- Thiết lập các khóa ngoại
ALTER TABLE N09_NHANSU
ADD
    CONSTRAINT FK_NV_DV 
    FOREIGN KEY (MADV)
    REFERENCES N09_DONVI(MADV);

ALTER TABLE N09_HOCPHAN
ADD
    CONSTRAINT FK_HP_DV 
    FOREIGN KEY (MADV)
    REFERENCES N09_DONVI(MADV);
    
ALTER TABLE N09_KHMO
ADD
    CONSTRAINT FK_KH_HP 
    FOREIGN KEY (MAHP)
    REFERENCES N09_HOCPHAN(MAHP);

ALTER TABLE N09_PHANCONG
ADD
    CONSTRAINT FK_GV_PC 
    FOREIGN KEY (MAGV)
    REFERENCES N09_NHANSU(MANV);

ALTER TABLE N09_PHANCONG
ADD
    CONSTRAINT FK_PC_KH 
    FOREIGN KEY (MAHP, HK, NAM, MACT)
    REFERENCES N09_KHMO(MAHP, HK, NAM, MACT);

ALTER TABLE N09_DANGKY
ADD
    CONSTRAINT FK_SV_PC 
    FOREIGN KEY (MAGV, MAHP, HK, NAM, MACT)
    REFERENCES N09_PHANCONG(MAGV, MAHP, HK, NAM, MACT);
/
