-- Lớp: CQ2021/1
-- Nhóm: 09
-- Thành viên:
-- 21120037 - Mã Thùy Anh
-- 21120060 - Nguyễn Long Giang
-- 21120082 - Phan Quốc Huy 
-- 21120117 - Lê Thị Hồng Phượng



----------------------------------------------------------------
-- Tạo User ADMIN với quyền hạn gần tương đương SYS
----------------------------------------------------------------
-- Xóa user ADMIN nếu trước khi tạo mới lại
ALTER SESSION SET "_ORACLE_SCRIPT" = TRUE;
DROP USER C##ADMIN CASCADE;
/

-- Tạo user ADMIN:
-- B1. Tạo Common User C##ADMIN (Password=123) trong CDB$ROOT
CREATE USER C##ADMIN IDENTIFIED BY 123 CONTAINER = ALL;
/

-- B2. Cấp quyền DBA CHO C##ADMIN
GRANT DBA TO C##ADMIN CONTAINER = ALL; 
/

-- B3. Cấp các quyền cao cấp trên toàn bộ CONTAINER
GRANT CREATE SESSION TO C##ADMIN CONTAINER = ALL; 
GRANT ALTER SESSION TO C##ADMIN CONTAINER = ALL;
GRANT EXECUTE ANY PROCEDURE TO C##ADMIN CONTAINER = ALL;
GRANT CONNECT TO C##ADMIN WITH ADMIN OPTION CONTAINER = ALL;
GRANT CREATE USER TO C##ADMIN CONTAINER = ALL;
GRANT CREATE ANY PROCEDURE TO C##ADMIN CONTAINER = ALL;
GRANT GRANT ANY ROLE TO C##ADMIN CONTAINER = ALL;
GRANT DROP USER TO C##ADMIN CONTAINER = ALL;
GRANT SELECT_CATALOG_ROLE TO C##ADMIN CONTAINER = ALL;
GRANT SELECT ANY DICTIONARY TO C##ADMIN CONTAINER = ALL;
/

-- CONNECT vào C##ADMIN để tạo CSDL trên Schema C##ADMIN 
CONN C##ADMIN/123;
/

----------------------------------------------------------------
-- Tạo CSDL cho đồ án
----------------------------------------------------------------
-- Xóa các bảng và user trước khi chạy script
DROP TABLE N09_NHANSU CASCADE CONSTRAINTS;
DROP TABLE N09_SINHVIEN CASCADE CONSTRAINTS;
DROP TABLE N09_DONVI CASCADE CONSTRAINTS;
DROP TABLE N09_HOCPHAN CASCADE CONSTRAINTS;
DROP TABLE N09_KHMO CASCADE CONSTRAINTS;
DROP TABLE N09_PHANCONG CASCADE CONSTRAINTS;
DROP TABLE N09_DANGKY CASCADE CONSTRAINTS;
/

-- Tạo CSDL
CREATE TABLE N09_NHANSU
(
    MANV CHAR(5),
    HOTEN NVARCHAR2(100),
    PHAI NVARCHAR2(3),
    NGSINH DATE,
    PHUCAP NUMBER(10),
    DT CHAR(10),
    VAITRO NVARCHAR2(30),
    MADV CHAR(5),
    
    PRIMARY KEY(MANV)
);

CREATE TABLE N09_SINHVIEN
(
    MASV CHAR(5),
    HOTEN NVARCHAR2(100),
    PHAI NVARCHAR2(3),
    NGSINH DATE,
    DIACHI NVARCHAR2(100),
    DT CHAR(10),
    MACT NVARCHAR2(30),
    MANGANH NVARCHAR2(30),
    SOTCTL NUMBER(4),
    DTBTL NUMBER(4,2),
    
    PRIMARY KEY(MASV)
);

CREATE TABLE N09_DONVI
(
    MADV CHAR(5),
    TENDV NVARCHAR2(100),
    TRGDV CHAR(5),
    
    PRIMARY KEY(MADV)
);

CREATE TABLE N09_HOCPHAN
(
    MAHP CHAR(5),
    TENHP NVARCHAR2(100),
    SOTC NUMBER(2),
    STLT NUMBER(4),
    STTH NUMBER(4),
    SOSVTD NUMBER(4),
    MADV CHAR(5),
    
    PRIMARY KEY(MAHP)
);

CREATE TABLE N09_KHMO
(
    MAHP CHAR(5),
    HK NUMBER(1),
    NAM NUMBER(4),
    MACT VARCHAR(4),
    
    PRIMARY KEY(MAHP, HK, NAM, MACT)
);

CREATE TABLE N09_PHANCONG
(
    MAGV CHAR(5),
    MAHP CHAR(5),
    HK NUMBER(1),
    NAM NUMBER(4),
    MACT VARCHAR(4),
    
    PRIMARY KEY(MAGV, MAHP, HK, NAM, MACT)
);

CREATE TABLE N09_DANGKY
(
    MASV CHAR(5),
    MAGV CHAR(5),
    MAHP CHAR(5),
    HK NUMBER(1),
    NAM NUMBER(4),
    MACT VARCHAR(4),
    DIEMTH NUMBER(4,2),
    DIEMQT NUMBER(4,2),
    DIEMCK NUMBER(4,2),
    DIEMTK NUMBER(4,2),
    
    PRIMARY KEY(MASV, MAGV, MAHP, HK, NAM, MACT)
);

-- Thiết lập các khóa ngoại
ALTER TABLE N09_NHANSU
ADD
    FOREIGN KEY (MADV)
    REFERENCES N09_DONVI(MADV);

ALTER TABLE N09_HOCPHAN
ADD
    FOREIGN KEY (MADV)
    REFERENCES N09_DONVI(MADV);
    
ALTER TABLE N09_KHMO
ADD
    FOREIGN KEY (MAHP)
    REFERENCES N09_HOCPHAN(MAHP);

ALTER TABLE N09_PHANCONG
ADD
    FOREIGN KEY (MAGV)
    REFERENCES N09_NHANSU(MANV);

ALTER TABLE N09_PHANCONG
ADD
    FOREIGN KEY (MAHP, HK, NAM, MACT)
    REFERENCES N09_KHMO(MAHP, HK, NAM, MACT);

ALTER TABLE N09_DANGKY
ADD
    FOREIGN KEY (MAGV, MAHP, HK, NAM, MACT)
    REFERENCES N09_PHANCONG(MAGV, MAHP, HK, NAM, MACT);
/
